repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        language: system
        entry: gitleaks detect --config=.gitleaks.toml --verbose --redact --no-git --source=.
        pass_filenames: false
