services:

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - D:/docker-data/postgres:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"

  kafka:
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ai-control-plane-kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  openbao:
    environment:
      BAO_DEV_ROOT_TOKEN_ID: dev-root-token
    ports:
      - "8200:8200"


  ollama:
    ports:
      - "11434:11434"
    volumes:
      - D:/docker-data/ollama:/root/.ollama